version: "3"
services:
  postgres:
    image: postgres:15-alpine
    container_name: grocer_postgres
    environment:
      POSTGRES_PASSWORD: neosfer
      POSTGRES_DB: movies
      POSTGRES_USER: neosfer
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgres/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/postgres/init.sql:/docker-entrypoint-initdb.d/02-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U neosfer -d movies"]
      interval: 5s
      timeout: 5s
      retries: 5
