CREATE TABLE "movie" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "year_of_release" int,
  "date_of_release" int,
  "description" text NOT NULL
);

CREATE TABLE "rating" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "value" smallint NOT NULL check (value between 1 and 50),
  "movie_id" int NOT NULL
);

CREATE TABLE "comment" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "value" text NOT NULL,
  "movie_id" int NOT NULL
);

ALTER TABLE "rating" ADD FOREIGN KEY ("movie_id") REFERENCES "movie" ("id") ON DELETE CASCADE;

ALTER TABLE "comment" ADD FOREIGN KEY ("movie_id") REFERENCES "movie" ("id") ON DELETE CASCADE;
