CREATE TABLE "movie" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "image" bytea,
  "release_year" int,
  "description" text NOT NULL
);

CREATE TABLE "rating" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "value" smallint NOT NULL,
  "movie_id" int NOT NULL
);

CREATE TABLE "comment" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "value" text NOT NULL,
  "movie_id" int NOT NULL,
  "creation_time" TIMESTAMP DEFAULT (NOW())
);

CREATE TABLE "wish_list" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "movie_id" int NOT NULL
);

ALTER TABLE "rating" ADD FOREIGN KEY ("movie_id") REFERENCES "movie" ("id") ON DELETE CASCADE;

ALTER TABLE "comment" ADD FOREIGN KEY ("movie_id") REFERENCES "movie" ("id") ON DELETE CASCADE;

ALTER TABLE "wish_list" ADD FOREIGN KEY ("movie_id") REFERENCES "movie" ("id") ON DELETE CASCADE;
