export const insertMovieQuery = `INSERT INTO movie(name, description, image, release_year) VALUES($1, $2, $3, $4) RETURNING *`;
export const insertRatingQuery = `INSERT INTO rating(movie_id, value) VALUES($1, $2) RETURNING *`;
export const insertCommentQuery = `INSERT INTO comment(movie_id, value) VALUES($1, $2) RETURNING *`;
export const insertWishlistQuery = `INSERT INTO wish_list(movie_id) VALUES($1) RETURNING *`;
export const listMoviesQuery = `SELECT id,name,description,encode(image, 'base64'),release_year FROM movie`;
export const listRatingsQuery = `SELECT * FROM rating WHERE movie_id = $1`;
export const listCommentsQuery = `SELECT * FROM comment WHERE movie_id = $1 ORDER BY id DESC`;
export const listWishlistQuery = `SELECT m.id, m.name, encode(m.image, 'base64'), m.release_year, m.description FROM movie m JOIN wish_list w ON m.id = w.movie_id;`;
export const getMovieQuery = `SELECT * FROM movie WHERE id = $1`;
export const deleteMovieQuery = `DELETE FROM movie WHERE id = $1`;
export const deleteCommentQuery = `DELETE FROM comment WHERE id = $1`;
export const deleteWishlistQuery = `DELETE FROM wish_list WHERE movie_id = $1`;
